services:
    dbpg:
        container_name: dbpg-web-node
        image: postgres:16.9-bullseye
        restart: always
        environment:
          - POSTGRES_USER=${PGUSER}
          - POSTGRES_PASSWORD=${PGPASSWORD}
        ports:
          - "${PGPORT}:${PGPORT}"
        volumes: 
          - ./src/sql/.:/docker-entrypoint-initdb.d/.
    web-node:
        container_name: web-node
        build:
          context: .
          dockerfile: Dockerfile.web-node
        env_file:
          - .env
        expose:
          - "${APP_PORT}"
        ports:
          - "${APP_PORT}:${APP_PORT}" 
        depends_on:
          - dbpg
        restart: always